#!/bin/bash

### BEGIN INIT INFO
 # Provides:          gramophono
 # Required-Start:    $all
 # Required-Stop:
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: RaspiPhono, mp3 player
 ### END INIT INFO

 # change directory
 cd /home/pi/RaspiPhono

 # execute
 python3 gramophono.py &

 exit 0